# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Imraan Abdullah's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Imraan Abdullah
headline: Civil Construction Engineer (Honours)
description: >- # dont remove this line. this will ignore all new lines until the next section
  I am a Washington Accord accredited Civil and Construction Engineer 
  with a 7.0/9.0 GPA from Auckland University of Technology. My 
  expertise spans structural design, geotechnical engineering, 
  project management, and construction materials. I am 
  proficient in industry-standard software including SAP2000, 
  Revit, Solidworks, and Microsoft Project. With hands-on 
  experience from university projects and internships, 
  I am seeking to apply my technical skills and 
  engineering knowledge to real-world projects in Perth.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing # or /assets/resume/resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: test    # https://www.linkedin.com/in/imraan-abdullah-aa23b7357/imraan11abdullah
  github: leea12    # https://github.com/{your url slug} 
  stackoverflow: test      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Engineering Design & Analysis
    tools:
    - Structural Design
    - Geotechnical Design
    - Engineering Design
    - Design Calculations
    - 3D Modelling
    - Foundation Design (deep & shallow foundations)
    - Soil Classification & Interpretation
    - Load Path Identification
  - category: Engineering Software
    tools:
    - SAP2000
    - Revit
    - Solidworks
    - Rhino 3D
    - QV Cost Builder
    - Microsoft Project (project management)
    - Microsoft Word (technical reports)
    - Microsoft PowerPoint (technical spreadsheets)
    - Microsoft PowerPoint (design presentations)
  - category: Construction & Project Management
    tools:
    - Project Coordination & Management
    - Quantity Surveying & Cost Control (fundamentals)
    - Scheduling & Construction Planning
    - Construction Methods & Sequencing
    - Construction Materials & Buildability
    - Off-Site & Prefabricated Construction Methods  
  - category: Technical Skills
    tools:
    - Applied Mathematics & Engineering Mechanics
    - Sustainable Design
    - Steel, Concrete & Timber Design
    - Reinforced Concrete Design
    - Soil Mechanics & Foundation Design
    - Engineering Judgement & Risk Awareness
  - category: Professional Skills
    tools:
    - Technical Communication
    - Multidisciplinary Teamwork
    - Task Prioritisation & Time Management
    - Engineering Problem Solving
    - Site Coordination & Field Awareness
    - Stakeholder & Contractor Liaison


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/xykklnql



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "##1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#3d3d3d"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "##1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
